name: California Commons
favicon: null
layout_spectrum: 0.42394
typography_spectrum: 0.5251614891458303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#de3129'
    - '#000000'
    - '#329401'
    - '#5c5c5c'
  brandStrength: 0.4375
  lightness: 0.708357541821897
  saturation: 0.5470392371062189
  rhythmicContrast: 0.10228336951695383
purpose: []
